fpath+=~/.zsh/functions

setopt NO_CASE_GLOB
setopt EXTENDED_HISTORY
# share history across multiple zsh sessions
setopt SHARE_HISTORY
# append to history
setopt APPEND_HISTORY
# adds commands as they are typed, not at shell exit
setopt INC_APPEND_HISTORY
# expire duplicates first
setopt HIST_EXPIRE_DUPS_FIRST 
# do not store duplications
setopt HIST_IGNORE_DUPS
#ignore duplicates when searching
setopt HIST_FIND_NO_DUPS
# removes blank lines from history
setopt HIST_REDUCE_BLANKS
# enable auto CD
setopt AUTO_CD

setopt CORRECT_ALL

autoload -Uz compinit && compinit
autoload colored_manpage && colored_manpage

# case insensitive path-completion
zstyle ':completion:*' matcher-list 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]} l:|=* r:|=*' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]} l:|=* r:|=*' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]} l:|=* r:|=*'

alias ls='ls -G'

#change up and down arrow so they search instead of just show prev command
bindkey $'^[[A' up-line-or-search    # up arrow
bindkey $'^[[B' down-line-or-search  # down arrow

# set EDITOR to bbedit
if [[ -x "/usr/local/bin/bbedit" ]]; then
	export EDITOR="/usr/local/bin/bbedit -w --resume"
fi

PROMPT='%(?.%F{green}🌈.%F{red}🔥 %?)%f %F{green}%1~%f%b %# '

repo_dir="~/.zsh/git"

# zsh-autosuggestions
# https://github.com/zsh-users/zsh-autosuggestions/blob/master/INSTALL.md
if [[ -f $repo_dir/zsh-autosuggestions/zsh-autosuggestions.zsh ]]; then
	source $repo_dir/zsh-autosuggestions/zsh-autosuggestions.zsh
fi

# zsh-syntax-highlighting
# (note, according to the docs, this must be loaded LAST)
# https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/INSTALL.md
if [[ -r $repo_dir/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]]; then
	source $repo_dir/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
fi

